version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - docker/install-docker-compose
      - run: docker-compose up -d
      - run: bash test.sh

workflows:
  integration_tests:
    jobs:
      - test